import { Metadata } from "next"
// This is Metadata
export const metadata : Metadata = {
    title: "About Page",
    description: "Generated by create next app",
  }

export default function About(){
    return <h1>This is About Page</h1>
}

