import { Metadata } from "next";

export async function generateMetadata({params}): Promise<Metadata>{
  return {
    title: "Home Page",
    description: "Generated by create next app",
  };
}

export default function Home() {
  return <h1>Home</h1>;
}
